# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [4]:
import numpy as np

In [15]:
def create_matrix(n):
  """
  In this function you should create matrix in order of n*n with random numbers 
  in the [n, n+100) interval.

  see the bellow link:
    https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

  Arguments:
    inputs:
      n: an integer describing the order of the matrix
    outputs:
      created matrix  
  """
  ##############################################
  ############ YOUR CODES GO HERE ##############
  matrix = np.random.randint(n , n+100 , (n , n))
  ##############################################

  return matrix

In [16]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
##############################################
############ YOUR CODES GO HERE ##############
def get_input():
  n = input()
  matrix = create_matrix(int(n))
  print(matrix)
  return matrix
##############################################

In [17]:
def count_digits(matrix):
  """
  In this function you should implement a routine to count the digits in the given matrix.

  Arguments:
    inputs:
      matrix: input matrix
    outputs:
      digits: a dictionary containing digits as its keys and the counted numbers as its value
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  digits = {}
  for i in range(len(matrix)):
    for j in range(len(matrix)):
      for p in str(matrix[i , j]):
        if p in digits:
          digits[p] += 1
        else:
          digits[p] = 1
  ##############################################

  return digits


In [18]:
"""
In this cell call the implemented function and print the result
"""

##############################################
############ YOUR CODES GO HERE ##############
m = get_input()
print(count_digits(m))
##############################################

3
[[49 19 50]
 [25 37 32]
 [85 18  4]]
{'4': 2, '9': 2, '1': 2, '5': 3, '0': 1, '2': 2, '3': 2, '7': 1, '8': 2}


## Part B

In [13]:
def traverse_matrix(matrix):
  """
  Traverse the input matrix in the given manner then print result

  Arguments:
    inputs:
      matrix: input matrix
    outputs
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  i = 0 
  j = 0

  ans = []
  ans.append((0, 0))
  while True:
    if j < len(matrix) - 1:
      j += 1
    else:
      i += 1
    while i < len(matrix) and j >= 0:
      ans.append((i , j))
      i += 1 
      j -= 1
    i -= 1
    j += 1

    if i < len(matrix) - 1 :
      i += 1
    else :
      j += 1
    
    while i >= 0 and j < len(matrix):
      ans.append((i , j))
      i -= 1
      j += 1
    
    if len(ans) == pow(len(matrix) , 2):
      break
    i += 1
    j -= 1

  print(ans)
  ##############################################

In [14]:
matrix = np.zeros((6 ,6))
traverse_matrix(matrix)


[(0, 0), (0, 1), (1, 0), (2, 0), (1, 1), (0, 2), (0, 3), (1, 2), (2, 1), (3, 0), (4, 0), (3, 1), (2, 2), (1, 3), (0, 4), (0, 5), (1, 4), (2, 3), (3, 2), (4, 1), (5, 0), (5, 1), (4, 2), (3, 3), (2, 4), (1, 5), (2, 5), (3, 4), (4, 3), (5, 2), (5, 3), (4, 4), (3, 5), (4, 5), (5, 4), (5, 5)]
