# Q4

## Part A

In [2]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

"""

##############################################
############ YOUR CODES GO HERE ##############
import numpy as np 
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([[1],[-1],[1]]) 
a2 = np.transpose(a) 

e = np.dot(a2, a)
#reverse the matrix
c = np.linalg.inv(e)
d = np.dot(a2 , b)
ans = np.dot(c, d)  
print(np.add(ans , a))

##############################################

[[0.78125  1.78125  2.78125 ]
 [4.       5.       6.      ]
 [7.171875 8.171875 9.171875]]


## Part B

In [ ]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  ##############################################
  ############ YOUR CODES GO HERE ##############
  
  res = np.zeros((3 , 3))

  for t in range(3):
    for p in range(3):
      hold = np.zeros((3 , 3))
      for i in range(3):
        for j in range(3):
          hold[i][j] = A[i][j] * B[i + t][j + p]
      res[p , t] = np.sum(hold)

  res
  ##############################################

  return res

In [ ]:
A = [[1, 1, 1] , [1, -9 , 1] , [1 , 1 ,1]]
B = [[1 , 1 , 1 , 1 ,1], [1, 2 , 2 , 2 , 1] , [1, 2 , 2 , 2 , 1] ,  [1, 2 , 2 , 2 , 1] ,  [1, 1 , 1 , 1, 1]]
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
