## Modifying the picture with opencv and numpy libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2

In [2]:
!wget -q https://github.com/AlexeyAB/darknet/releases/download/yolov4/yolov7.weights 

In [3]:
!wget -q https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov7.cfg

In [4]:
net = cv2.dnn.readNetFromDarknet('yolov7.cfg', 'yolov7.weights')
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_OPENCV)

In [5]:
yolo_model = cv2.dnn_DetectionModel(net)
yolo_model.setInputParams(size=(1280, 1280), scale=1 / 255, swapRB=True)

**Just run the above cells without any changes**

In [7]:
"""
Please read the provided image in RGB with opencv lib and print the matrices

see bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.maximum.html
https://numpy.org/doc/stable/reference/generated/numpy.minimum.html
https://numpy.org/doc/stable/reference/generated/numpy.mean.html
"""
image = cv2.imread('Q5.png')
print(image.shape)
print(image.dtype)
print(np.mean(image))
print(np.max(image))
print(np.min(image))
print(image[:, :,0])
print("########################################################")
print(image[:, :,0] , image[:, :,1] , image[:, :,2])

(721, 1281, 3)
uint8
139.98719468688319
255
0
[[126 113 152 ... 154 154 154]
 [128 128 149 ... 154 153 154]
 [135 156 148 ... 153 153 153]
 ...
 [122 122 123 ... 139 138 139]
 [123 124 124 ... 139 139 139]
 [123 123 123 ... 138 137 137]]
########################################################
[[126 113 152 ... 154 154 154]
 [128 128 149 ... 154 153 154]
 [135 156 148 ... 153 153 153]
 ...
 [122 122 123 ... 139 138 139]
 [123 124 124 ... 139 139 139]
 [123 123 123 ... 138 137 137]] [[147 136 175 ... 191 191 191]
 [149 149 172 ... 191 190 191]
 [156 177 171 ... 190 190 190]
 ...
 [121 121 122 ... 142 141 142]
 [122 123 123 ... 142 142 142]
 [122 122 122 ... 141 140 140]] [[144 132 171 ... 189 189 187]
 [146 146 168 ... 189 188 187]
 [153 174 167 ... 188 188 186]
 ...
 [107 107 108 ... 140 139 140]
 [108 109 109 ... 140 140 140]
 [108 108 108 ... 139 138 138]]


In [8]:

#### Just run this cell 


CONFIDENCE_THRESHOLD = 0.2
NMS_THRESHOLD = 0.4 

classes, scores, boxes = yolo_model.detect(image, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)

detections = [(box, score) for classid, score, box in zip(classes, scores, boxes)]

the result of the detection is classes of each object, 
confidence of predicting the class of that object and parameters of the bounding box

for every bounding box, we have bellow information:

x_min: the x coordinate of the left up corner of the bounding box

y_min: the y coordinate of the left up corner of the bounding box

w: the width of the bounding box

h: the height of the bounding box

In [ ]:
### please print the details of the detections
for x in detections:
  for y in x[0]:
    print(y) 
  print(x[1])
  print("####")


In [10]:
def visualize(frame, detections):
  """
  Draw all bounding boxes on the main original image and show the result
  Then save result with result.png name

  see the bellow links:
  https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html
  https://www.geeksforgeeks.org/python-opencv-cv2-imwrite-method/
  """

  ########################################
  ########### YOUR CODES GO HERE #########
  
  for x in detections:
    generated_img = cv2.rectangle(frame , pt1 = (x[0][0] , x[0][1]), pt2 = (x[0][0] + x[0][2] , x[0][1] + x[0][3]) , color=(255,0,0), thickness=2)
  cv2.imwrite("result.png", generated_img)

  ########################################

In [11]:
visualize(image, detections)

In [12]:
# Check if file has been saved or not
!(ls result.png && echo yes) || echo no

result.png
yes
